version: '3.8'
services:

  db:
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_DATABASE=conventionbooking
      - MYSQL_ROOT_PASSWORD=qwerty1234
    ports:
      - '3306:3306'
    volumes:
      - db:/var/lib/mysql

volumes:
  db:
    driver: local